export const dataLib = [
  {
    word: "chat",
    partOfSpeach: "",
    definition: "cat",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "dan",
    partOfSpeach: "",
    definition: "teeth",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "bak",
    partOfSpeach: "",
    definition: "crab",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "chèz",
    partOfSpeach: "",
    definition: "chair",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "dé",
    partOfSpeach: "",
    definition: "two",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "djól",
    partOfSpeach: "",
    definition: "pig",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "né",
    partOfSpeach: "",
    definition: "nose",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "bèf",
    partOfSpeach: "",
    definition: "beef",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "pen",
    partOfSpeach: "",
    definition: "bread",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "fèt",
    partOfSpeach: "",
    definition: "party",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "gason",
    partOfSpeach: "",
    definition: "boy",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "hach",
    partOfSpeach: "",
    definition: "axe",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "tifi",
    partOfSpeach: "",
    definition: "girl",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "jako",
    partOfSpeach: "",
    definition: "bird",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "kat",
    partOfSpeach: "",
    definition: "four",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "liv",
    partOfSpeach: "",
    definition: "book",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "mouton",
    partOfSpeach: "",
    definition: "sheep",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "nich",
    partOfSpeach: "",
    definition: "nest",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "zong",
    partOfSpeach: "",
    definition: "finger",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "koko",
    partOfSpeach: "",
    definition: "chocholate",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "pòpòt",
    partOfSpeach: "",
    definition: "doll",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "bonbon",
    partOfSpeach: "",
    definition: "cake",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "souwi",
    partOfSpeach: "",
    definition: "mouse",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "pòt",
    partOfSpeach: "",
    definition: "pot",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "radyo",
    partOfSpeach: "",
    definition: "radio",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "fèt",
    partOfSpeach: "",
    definition: "seven",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "tab",
    partOfSpeach: "",
    definition: "table",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "tjè",
    partOfSpeach: "",
    definition: "heart",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "vè",
    partOfSpeach: "",
    definition: "worm",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "wat",
    partOfSpeach: "",
    definition: "rat",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "yanm",
    partOfSpeach: "",
    definition: "yam",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
  {
    word: "zé",
    partOfSpeach: "",
    definition: "egg",
    egSentence: "",
    synonym: "",
    antonym: "",
    crossReference: "",
    etymology: "",
  },
];
